#!/bin/bash

echo "=> Triggering build for ireceptor/service-php-mongodb"
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" https://cloud.docker.com/api/build/v1/source/07ece7a8-52da-40d6-bfca-ebf105d3cde3/trigger/c2a50534-97de-46be-9fb6-5acbca33090f/call/

echo "=> Triggering build for ireceptor/dataloading-mongo"
curl -X POST -H "Content-Type: application/x-www-form-urlencoded" https://cloud.docker.com/api/build/v1/source/c9512b4b-1044-4db5-a70d-47aa693db152/trigger/8efd268a-4999-46b1-a503-aec7d2bf2fb0/call/
